[build]
  command = "hugo --gc --minify"
  publish = "public"


[context.production]
  command = "hugo --gc --minify"
  publish = "public"
  HUGO_VERSION = "0.141.0"  # Replace with latest Hugo version