baseURL = "http://localhost:1313/"
languageCode = "en-us"
theme = "adritian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]
  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.header]]
  name = "Projects"
  URL = "#portfolio"
  weight = 2

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 3


[params]

  sections = ["showcase", "about", "projects", "education", "experience", "contact"]

  homepageExperienceCount = 6

  # controls vercel page insights - disabled by default
  vercelPageInsights = false
  vercelAnalytics = false
  
  [params.google_analytics]
      code = ""
      enabled = false
  [params.google_tag_manager]
      code = ""
      enabled = false
  
  [params.logo]
    text1 = "Pranav Sharma"
  [params.footer]
      copyright = "© 2024 Pranav Sharma. All Rights Reserved."

